### ISSUE TITLE
MQTT over Websockets isn't working for the `mqtt.kafka.broker` example

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla-examples#132]
The `mqtt.kafka.broker` example `ws` endpoints don't work and throw the below errors.

using emqx: `Error: Connection refused: Protocol Error`

wscat:
```
% wscat -c ws://localhost:7114/ -s mqtt
Connected (press CTRL+C to quit)
Disconnected (code: 1005, reason: "")
% wscat -c wss://localhost:7143/ --ca mqtt.kafka.broker/tls/test-ca.crt -s mqtt
Connected (press CTRL+C to quit)
Disconnected (code: 1005, reason: "")
```

**Comment by jfallows** [comment]
This behavior is expected due to lack of `mqtt` `CONNECT` frame being sent over the websocket connection.

However, there was an issue that has now been resolved via linked PR and MQTTX client can be used to verify MQTT over WS works with latest `develop-SNAPSHOT` build, and will be included in the next release.
