### ISSUE TITLE
mqtt and consumer groups

### ISSUE THREAD

**Issue by ra014620** [aklivity/zilla-examples#74]
I'm running the mqtt.kafka.broker example without modification except for the chart version number is 0.9.54
Each time I publish a message with mosquito:
mosquitto_pub -V 'mqttv5' --topic 'zilla' --message 'Hello, world' --debug --insecure
it works but creates a new consumer group.  Is this normal?

**Comment by jfallows** [comment]
@ra014620 thanks for your question!

Zilla maps MQTT client sessions to Kafka using a combination of the following:
 - a message keyed by `client-id` in the log compacted `mqtt-sessions` topic to track client subscriptions across client reconnect, and
 - a consumer group derived from `client-id` to support session takeover and (in development) track QoS 1 and QoS 2 acknowlegement via consumer offsets

Unlike typical consumer group usage, our approach minimizes the number of hearbeats required to approximately one per MQTT session expiry interval.

When an MQTT session expires, perhaps because the MQTT client abruptly disconnected but did not reconnect, the corresponding consumer group also expires and the associated tracking state is cleaned up automatically.


Each successive invocation of `mosquitto_pub` generates a unique `client-id` of the form `mosquitto_pub_<PID>`, causing a distinct consumer group to be created because each time the `PID` is different.

```
% mosquitto_pub --help

...
-i : id to use for this client. Defaults to mosquitto_pub_ appended with the process id.
...
```

Specifying the `client-id` explicitly on the command line causes the same value to be used across successive invocations instead.

```
mosquitto_pub -V 'mqttv5' --topic 'zilla' --message 'Hello, world' --debug --insecure -i my-client-id-1
```

Hope this is helpful!

**Comment by ra014620** [comment]
I tried the -i option and it only created one consumer group but there was a different issue. Every other message times out with the message   "Error: Keepalive exceeded".   Any idea why that is?

**Comment by bmaidics** [comment]
Hi @ra014620 ,
Could you describe what's the workflow you're trying exactly? Based on your response, I'm assuming you're producing one message at a time using a different execution of mosquitto_pub each time using the same client-id.
I've tried that locally, and seems like it's working on my end. Here's what I did:
```
mosquitto_pub -V 'mqttv5' --topic 'zilla' --message 'Hello, world' --debug --insecure -i my-client-id-1
Client my-client-id-1 sending CONNECT
Client my-client-id-1 received CONNACK (0)
Client my-client-id-1 sending PUBLISH (d0, q0, r0, m1, 'zilla', ... (12 bytes))
Client my-client-id-1 sending DISCONNECT


mosquitto_pub -V 'mqttv5' --topic 'zilla' --message 'Hello, world' --debug --insecure -i my-client-id-1
Client my-client-id-1 sending CONNECT
Client my-client-id-1 received CONNACK (0)
Client my-client-id-1 sending PUBLISH (d0, q0, r0, m1, 'zilla', ... (12 bytes))
Client my-client-id-1 sending DISCONNECT

mosquitto_pub -V 'mqttv5' --topic 'zilla' --message 'Hello, world' --debug --insecure -i my-client-id-1
Client my-client-id-1 sending CONNECT
Client my-client-id-1 received CONNACK (0)
Client my-client-id-1 sending PUBLISH (d0, q0, r0, m1, 'zilla', ... (12 bytes))
Client my-client-id-1 sending DISCONNECT
```

Also, which Kafka and Zilla versions are you using? Just trying to make sure we're doing the exact same thing with the same versions so I can identify a potential bug on our side.
When you're saying you're seeing Zilla pods in terminating state, can you check Zilla logs? Maybe there was a crash and that's why Zilla did not answer, hence the keep-alive timeout?

**Comment by ra014620** [comment]
I cloned zilla-examples/mqtt.kafka.broker, then ran the setup.sh script. The versions of kafka and zilla would be whatever version the chart says to pull. 

I'm using mosquito_pub exactly like you're showing above.  The first message succeeds. The second message hangs for a bit and then exits with the error message:  Keepalive exceeded.  This pattern repeats. 

`% mosquitto_pub -V 'mqttv5' --topic 'zilla' --message 'Hello, world' --debug --insecure -i my-client-id-1
Client my-client-id-1 sending CONNECT
Client my-client-id-1 received CONNACK (0)
Client my-client-id-1 sending PUBLISH (d0, q0, r0, m1, 'zilla', ... (12 bytes))
Client my-client-id-1 sending DISCONNECT

 % mosquitto_pub -V 'mqttv5' --topic 'zilla' --message 'Hello, world' --debug --insecure -i my-client-id-1
Client my-client-id-1 sending CONNECT
Error: Keepalive exceeded
`
Nothing in the zilla log other than printing the config ending with the "started" message

I increased my virtual machine memory and I don't see any more terminating pods. 
I'm running this on MacOS Rancher Desktop 1.9.1, kubernetes version 1.24.15

**Comment by bmaidics** [comment]
Thanks for the thorough description @ra014620 with the help of that, I'm able to reproduce this issue. 
It seems to be a legit bug on our side, we're already looking into it. We will update here once we're able to provide more information.

**Comment by jfallows** [comment]
@ra014620 we believe we have identified the issue and are in final testing of a fix - will keep you posted.

**Comment by jfallows** [comment]
@ra014620 we have addressed the reported issue and verified that we can no longer reproduce.

Please update to latest `zilla-examples` to pick up latest helm chart and latest zilla version to confirm.

**Comment by ra014620** [comment]
Confirmed that it works for me. Thank you!

**Comment by jfallows** [comment]
Thanks @ra014620 please let us know if you have any more questions, we are happy to help!
